### ISSUE TITLE
cleanPhoneNumber only working for 10-digit numbers

### ISSUE THREAD

**Issue by micahcowan** [jashort/kumoreg#1]
In the newly added `cleanPhoneNumber` method of `AttendeeImporterService.java`, there's the bit starting at line 179 (of commit d26e5a1a):

```
        if (p.matches("\\d{10}")) {
            output = p.substring(0, 3) + "-" + p.substring(3, 6) + "-" + p.substring(6, 10);
        } else {
            output = phoneNumber.replaceAll("^\\+[^0-9 -]", "").trim();
        }
```

If the `p.matches` expression is true, everything works out as expected, but if it gets to the branch with the `replaceAll`, that doesn't really weed anything out. The most it will do is remove the first two characters of the phone number, if they happen to be a "+" followed by a non-digit-space-or-dash.

I thought maybe you might want something like `.replaceAll("[^0-9 +-]", "")`, which would strip out everything but digits, spaces, or dashes, but then that doesn't really do the right thing with a phone number like "206-233-1419 x10349", which would just become "206-233-1419 10349". Honestly I'm not sure what the right thing to do with something like that is... maybe you need another, separate replacement for dealing with extension numbers like that?

(The phone number given in the paragraph above comes from "Dana Monahan" in the import data set - if you search for that attendee you'll see it imported as-is from `text.csv`)

**Comment by jashort** [comment]
My original intention was something like:
1) Remove everything but digits
2) If 10 digits are left, format it like a phone number ("xxx-xxx-xxxx")
3) Otherwise, assume it's an international number. Remove letters but don't try to format it nicely.

However, you're right:
1) 3 doesn't work with the regex there now
2) An "x" will break validation for phone numbers on the form #2 
3) The "x" will get lost.

Thinking about it the other way around, these seem like "good" numbers: 
123-123-1234
123-123-1234 x5678
867-5309
+64 6-759 1234

So I'll also need to adjust the form validation to include "x" and "+"

**Comment by jashort** [comment]
Cleaned that up some. Note that I'm not checking for anything too crazy, like multiple "x"'s or a "+" somewhere besides the first character. I want to clean things up as much as possible, but if someone really wants to go nuts with the phone number, who am I to stop them? :)
